### ISSUE TITLE
tf GPU镜像运行DIEN，只能用CPU训练

### ISSUE THREAD

**Issue by Phoenixinfire** [alibaba/x-deeplearning#109]
config: {u'checkpoint': {u'save_interval': 1000, u'output_dir': u'./ckpt_dir/'}, u'job_type': u'train', u'model': u'dien', u'seed': 3, u'data_dir': u'/data/raw_data/'}
WARNING:tensorflow:From /data/x-deeplearning/xdl-algorithm-solution/DIEN/script/utils.py:37: calling __init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
facts_size 36
querry_size 36
[WARNING]: no gradient found for var:tf_model/bn1/moving_mean under scope:train , maybe not used?
[WARNING]: no gradient found for var:tf_model/bn1/moving_variance under scope:train , maybe not used?
facts_size 36
querry_size 36
2019-01-30 08:31:49.246288: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-01-30 08:31:49.246362: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:157] no NVIDIA GPU device is present: /dev/nvidia0 does not exist

只能用CPU训练
镜像版本：registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-tf1.12

**Comment by Phoenixinfire** [comment]
宿主机器是有GPU的，且安装了驱动，运行nvidia-smi可以看到显卡信息，运行tensorflow 官方的GPU镜像版本也没问题。

**Comment by yiling-dc** [comment]
这个任务是用xdl_submit.py提交的吗？如果是的话，麻烦提供一下完整的json配置文件

**Comment by Phoenixinfire** [comment]
@yiling-dc 不是，是xdl-algorithm-solution\DIEN 实现的例子。python train.py --run_mode=local --config=config.json。
config.json
{
  "checkpoint": {
    "output_dir": "./ckpt_dir/",
    "save_interval": 1000
  },
  "data_dir": "/data/raw_data/",
  "seed": 3,
  "job_type": "train",
  "model": "dien"
}

**Comment by yiling-dc** [comment]
> @yiling-dc 不是，是xdl-algorithm-solution\DIEN 实现的例子。python train.py --run_mode=local --config=config.json。
> config.json
> {
> "checkpoint": {
> "output_dir": "./ckpt_dir/",
> "save_interval": 1000
> },
> "data_dir": "/data/raw_data/",
> "seed": 3,
> "job_type": "train",
> "model": "dien"
> }

启动docker的时候可有挂载显卡驱动和device？

**Comment by Phoenixinfire** [comment]
@yiling-dc 更换容器中的驱动版本，可以正常运行了
