### ISSUE TITLE
gpu版本容器内无法使用nvidia-smi等命令

### ISSUE THREAD

**Issue by huipingC** [alibaba/x-deeplearning#28]
使用XDL Docker镜像registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-tf1.12，在服务器上进行测试，但是容器内使用nvidia-smi等命令，会报错Failed to initialize NVML: Unknown Error。同时跑demo时，仅能以cpu方式训练模型，无法使用gpu。
我们的服务器系统是centos，有安装docker，是否和ubuntu系统驱动不兼容，还是有其他原因？

**Comment by DeliangFan** [comment]
补充下，我们 Nvidia 版本是 Driver Version: 390.77

**Comment by guoxinyang** [comment]
@huipingC @DeliangFan 有两种可能，第一种是nvidia-docker的问题，可以改为使用下面的命令运行
sudo docker run `curl http://localhost:3476/v1.0/docker/cli` -it registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-tf1.12 /bin/bash
第二种可能是 docker里面安装的是410.72 的driver，我们在Driver Version: 384.81  的机器上实测，虽然使用不了nvidia-smi，但是GPU是可以正常使用的，如果一定要使用nvidia-smi，你可以尝试把镜像里的driver版本改为 Driver Version: 390.77。

**Comment by zhaoyu87** [comment]
> @huipingC @DeliangFan 有两种可能，第一种是nvidia-docker的问题，可以改为使用下面的命令运行
> sudo docker run `curl http://localhost:3476/v1.0/docker/cli` -it registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-tf1.12 /bin/bash
> 第二种可能是 docker里面安装的是410.72 的driver，我们在Driver Version: 384.81 的机器上实测，虽然使用不了nvidia-smi，但是GPU是可以正常使用的，如果一定要使用nvidia-smi，你可以尝试把镜像里的driver版本改为 Driver Version: 390.77。

我这里driver version也是384.81，运行example时会报兼容错误，如下。另外请问如何修改镜像里面的driver版本，非常感谢 @guoxinyang 

2019-01-30 14:15:23.041010: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2019-01-30 14:15:23.041129: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: 8294c4ac4c8f
2019-01-30 14:15:23.041161: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: 8294c4ac4c8f
2019-01-30 14:15:23.041312: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.72.0
2019-01-30 14:15:23.041382: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 384.81.0
2019-01-30 14:15:23.041405: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:308] kernel version 384.81.0 does not match DSO version 410.72.0 -- cannot find working devices in this configuration

**Comment by DeliangFan** [comment]
> @huipingC @DeliangFan 有两种可能，第一种是nvidia-docker的问题，可以改为使用下面的命令运行
> sudo docker run `curl http://localhost:3476/v1.0/docker/cli` -it registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-tf1.12 /bin/bash
> 第二种可能是 docker里面安装的是410.72 的driver，我们在Driver Version: 384.81 的机器上实测，虽然使用不了nvidia-smi，但是GPU是可以正常使用的，如果一定要使用nvidia-smi，你可以尝试把镜像里的driver版本改为 Driver Version: 390.77。

我们把容器内部的 driver 替换成和宿主机一样好，一切正常了！

**Comment by zhaoyu87** [comment]
@DeliangFan 我也遇到了同样的问题，请问是怎么替换的啊，多谢

**Comment by DeliangFan** [comment]
> 替换

把容器内部的 nvidia 相关的 debian 包卸载，然后从 nvidia 官网下载对应版本的驱动安装即可。

**Comment by xzy256** [comment]
安装新的 NVIDIA 驱动会报"An NVIDIA kernel module 'nvidia-uvm' appears to already be loaded in your kernel ... ..."错误怎么解决的？
```
# lsmod | grep -i nvidia
nvidia_uvm            791827  0
nvidia_drm             43787  0
nvidia_modeset       1082590  1 nvidia_drm
nvidia              17596973  23 nvidia_modeset,nvidia_uvm
ipmi_msghandler        46608  5 ipmi_devintf,ipmi_poweroff,ipmi_watchdog,nvidia,ipmi_si
drm_kms_helper        159169  2 nouveau,nvidia_drm
drm                   370825  5 ttm,drm_kms_helper,nouveau,nvidia_drm
i2c_core               40756  6 drm,igb,drm_kms_helper,i2c_algo_bit,nvidia,nouveau
```

**Comment by biaochen** [comment]
我也遇到了上面的问题，尝试在容器里重新安装驱动，modprobe -r nvidia-uvm 报了上面一样的错误。卡在这了。

**Comment by ideal-lee** [comment]
> 安装新的 NVIDIA 驱动会报"An NVIDIA kernel module 'nvidia-uvm' appears to already be loaded in your kernel ... ..."错误怎么解决的？
> 
> ```
> # lsmod | grep -i nvidia
> nvidia_uvm            791827  0
> nvidia_drm             43787  0
> nvidia_modeset       1082590  1 nvidia_drm
> nvidia              17596973  23 nvidia_modeset,nvidia_uvm
> ipmi_msghandler        46608  5 ipmi_devintf,ipmi_poweroff,ipmi_watchdog,nvidia,ipmi_si
> drm_kms_helper        159169  2 nouveau,nvidia_drm
> drm                   370825  5 ttm,drm_kms_helper,nouveau,nvidia_drm
> i2c_core               40756  6 drm,igb,drm_kms_helper,i2c_algo_bit,nvidia,nouveau
> ```
> 
> 尝试移除，找不到模块
> 
> ```
> # modprobe -r nvidia-uvm
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.0-693.el7.x86_64/modules.dep.bin'
> ```

您好，请问问题解决了么，遇到了相同的问题，很抓狂
